name: Backend Build Workflow for Development

on:
  pull_request:
    branches: [ "development" ]
    paths:
      - 'src/**/*'
      - 'Dockerfile'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn clean install -DskipTests
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .