name: Build Workflow for Development

on:
  pull_request:
    branches: [ "development" ]
    paths:
      - 'src/**/*'
      - 'Dockerfile'
      - 'view/**/*'
      - 'view/Dockerfile'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'src/**/*') || contains(github.event.pull_request.changed_files, 'Dockerfile')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and test backend
        run: mvn clean install -DskipTests

      - name: Build backend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

  build-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'view/**/*') || contains(github.event.pull_request.changed_files, 'view/Dockerfile')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test frontend
        run: |
          cd view
          npm install
          npm run build

      - name: Build frontend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./view