name: Frontend CI/CD for Production

on:
  push:
    branches: [ "production" ]
    paths:
      - 'view/**/*'
      - 'view/Dockerfile'

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd view
          npm install
          npm run build
      - run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./view
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
      - name: SSH and Deploy Frontend to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            cd kryptonite
            docker compose pull frontend
            docker compose up -d frontend