name: Frontend CI/CD for Production

# Trigger: Activates on push events to the 'production' branch, specifically for changes in the 'view' directory or Dockerfile.
on:
  push:
    branches: [ "production" ]
    paths:
      - 'view/**/*'   # Monitors changes in any file within the 'view' directory.
      - 'view/Dockerfile' # Monitors changes in the Dockerfile located in the 'view' directory.

# Job Definition: Defines a single job for building and deploying the frontend.
jobs:
  build-and-deploy-frontend:
    # Run Environment: Executes the job on the latest Ubuntu runner provided by GitHub.
    runs-on: ubuntu-latest

    # Steps: A sequence of steps that the job will execute.
    steps:
      - uses: actions/checkout@v2
        # Checkout Step: Checks out the code in the branch to the runner.

      - run: |
          cd view
          npm install
          npm run build
        # Build Frontend: Changes directory to 'view', installs dependencies, and builds the frontend application.

      # DockerHub Login: Logs into DockerHub using credentials stored in GitHub secrets.
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Build and Push: Builds and pushes Docker images to DockerHub.
      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./view
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # SSH and Deployment: SSH into a VM and deploys the frontend using Docker Compose.
      - name: SSH and Deploy Frontend to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            cd kryptonite
            docker compose pull frontend
            docker compose up -d frontend
